server:
  port: 8080

spring:
  datasource:
    driverClass: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: ture
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: 3.0

loan:
  message: "Welcome to NaviBank accounts related APIs"
  contactDetails:
    name: "John Doe"
    email: "john@gmail.com"
  onCallSupport:
    - (555) 555 1234
    - (555) 555 4321