services:
  accountsdb:
    container_name: "accountsdb"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: db-config

  loansdb:
    container_name: "loansdb"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: db-config

  cardsdb:
    container_name: "cardsdb"
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: db-config

  configserver:
    image: "hcnaveen/configserver:s5"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-network-config

  accounts:
    image: "hcnaveen/accounts:s5"
    container_name: "accounts-ms"
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: base-network-env-config

  loans:
    image: "hcnaveen/loans:s5"
    container_name: "loans-ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
        SPRING_APPLICATION_NAME: "loans"
        SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: base-network-env-config

  cards:
    image: "hcnaveen/cards:s5"
    container_name: "cards-ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: base-network-env-config


networks:
  navibank:
    driver: "bridge"

#services:
#  rabbitmq:
#    image: "rabbitmq:3.13-management"
#    hostname: "rabbitmq"
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: rabbitmq-diagnostic check_port_connectivity
#      start_period: 5s
#      timeout: 5s
#      interval: 10s
#      retries: 10
#    networks:
#      - naviBank
#
#  configserver:
#    image: "hcnaveen/configserver:s5"
#    container_name: "configserver-ms"
#    ports:
#      - 8071:8071
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/readiness | grep UP || exit 1"
#      start_period: 10s
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#
#  accounts:
#    image: "hcnaveen/accounts:s5"
#    container_name: "account-ms"
#    ports:
#      - 8070:8070
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_CONFIG_IMPOST: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#  loan:
#    image: "hcnaveen/loan:s5"
#    container_name: "loan-ms"
#    ports:
#      - 8080:8080
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "loan"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserve:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#  cards:
#    image: "hcnaveen/cards:s5"
#    container_name: "card-ms"
#    ports:
#      - 8090:8090
#    depends_on:
#      -configserver:
#         condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#      SPRING_CONFIG_IMPORT: "configserve:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#
#networks:
#  naviBank:
#    driver: "bridge"