services:
  redis:
    container_name: naviredis
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      interval: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-config

  configserver:
    image: "hcnaveen/configserver:s8"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-config

  eurekaserver:
    image: "hcnaveen/eurekaserver:s8"
    container_name: "eurekaserver-ms"
    ports:
      - 8060:8060
    healthcheck:
      test: "curl --fail --silent localhost:8060/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 10
      interval: 10s
      timeout: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: network-deploy-env-config

  accounts:
    image: "hcnaveen/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: app-config

  loans:
    image: "hcnaveen/loans:s8"
    container_name: "loans-ms"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
        SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: app-config

  cards:
    image: "hcnaveen/cards:s8"
    container_name: "cards-ms"
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: app-config

  gatewayserver:
    image: "hcnaveen/gatewayserver:s8"
    container_name: "gatewayserver-ms"
    ports:
      - 8050:8050
    healthcheck:
      test: "curl --fail --silent localhost:8050/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT_TIMEOUT: 1s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: app-config

networks:
  naviBank:
    driver: "bridge"

#services:
#  rabbitmq:
#    image: "rabbitmq:3.13-management"
#    hostname: "rabbitmq"
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: rabbitmq-diagnostic check_port_connectivity
#      start_period: 5s
#      timeout: 5s
#      interval: 10s
#      retries: 10
#    networks:
#      - naviBank
#
#  configserver:
#    image: "hcnaveen/configserver:s4"
#    container_name: "configserver-ms"
#    ports:
#      - 8071:8071
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/readiness | grep UP || exit 1"
#      start_period: 10s
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#
#  accounts:
#    image: "hcnaveen/accounts:s4"
#    container_name: "account-ms"
#    ports:
#      - 8070:8070
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_CONFIG_IMPOST: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#  loan:
#    image: "hcnaveen/loan:s4"
#    container_name: "loan-ms"
#    ports:
#      - 8080:8080
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "loan"
#      SPRING_CONFIG_IMPORT: "configserver:http://configserve:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#  cards:
#    image: "hcnaveen/cards:s4"
#    container_name: "card-ms"
#    ports:
#      - 8090:8090
#    depends_on:
#      -configserver:
#         condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - naviBank
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#      SPRING_CONFIG_IMPORT: "configserve:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: default
#
#
#networks:
#  naviBank:
#    driver: "bridge"