server:
  port: 8080

spring:
  application:
    name: "loans"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"